### PR TITLE
Add system configuration for the Kolibri dbus daemon

### PR DESCRIPTION
**Pull request by dylanmccall**
This depends on changes to Kolibri pending review in flathub/org.learningequality.Kolibri#17, but I believe it is safe to merge at any time.

https://phabricator.endlessm.com/T31182

### CODE REVIEW

**Comment by dylanmccall** [comment]
Things to test here:

- A "kolibri" system user is created. This is both for upgrading Endless OS, and for new installs. (That isn't really changed in this branch, but we never actually had this stuff in a release so it's worth making sure).
- The newest (unreleased) version of the Kolibri flatpak app works, using a Kolibri instance with a home directory located at `/var/lib/kolibri/data`.

**Comment by dylanmccall** [comment]
To test this, we need an early version of the Kolibri flatpak:

Build and install org.learningequality.Kolibri.Devel from https://github.com/learningequality/kolibri-installer-gnome/pull/14.

Next, build and install this package from source with the `kolibri_flatpak_id` option set accordingly:

```
meson . build --prefix=/usr -Dkolibri_flatpak_id=org.learningequality.Kolibri.Devel
ninja -C build install
```

**Review by jprvita — APPROVED** [review]
The whole D-Bus + systemd approach looks correct and sensible to me. The only question I had is about the KOLIBRI_USER management, but it looks like we already have a user named `kolibri` in the system, so we are good there. Otherwise I would suggest for us to use systemd's `DynamicUser=` setting instead.

I don't know Kolibri too deeply, so take my CR+ with a grain of salt.

**Review by manuq — COMMENTED** [review]
Looks good to me as well!

**Comment by dylanmccall** [comment]
Hm, now you mention it, I do wonder why we aren't using `DynamicUser`. I vaguely recall discussing that when we did eos-kolibri originally, but can't find an email about it so I might be imagining. I'll try that and see what happens, but perhaps in a separate branch :)

**Comment by jprvita** [comment]
> Hm, now you mention it, I do wonder why we aren't using `DynamicUser`. I vaguely recall discussing that when we did eos-kolibri originally, but can't find an email about it so I might be imagining. I'll try that and see what happens, but perhaps in a separate branch :)

If we were to switch it now, we'd have to drop the created kolibri user by reverting https://github.com/endlessm/base-passwd/commit/c12a43381beefa5a7b6d1b41bafa4438d1ec2a0f. The only problem I can think from the top of my head is that if there are any files owned by that user, they would need to be dealt with (since they would have the old uid/gid). I don't know from the top of my head how `DynamicUser` deals with file ownership.

**Comment by dylanmccall** [comment]
Ah, happily DynamicUser has migrations like that in mind and will behave as usual if there's an existing `kolibri` user. Alas, one other issue, but I made a draft pull request to explore the idea: https://github.com/endlessm/eos-kolibri/pull/2.

**Pull request merged**
