### PR TITLE
tmpfiles: Don't recursively adjust permissions

### PR DESCRIPTION
**Pull request by wjt**
Previously, at startup all files and directories below /var/lib/kolibri
and /var/lib/endless-key would be adjusted to be owned by the 'kolibri'
user and group, and to have mode 0755 (readable and executable by all;
writable by the owner).

Since
https://github.com/endlessm/eos-image-builder/commit/2f47bc972bddc7ded93be9a26f68c68cde427441
the change of ownership is unnecessary:

- All pre-loaded resources in new images will be owned by the correct
  user and group
- All existing systems, installed from images where the files were owned
  by root, have booted at least once and so have had the ownership
  updated
- The systemwide daemons run as the 'kolibri' user and group so any new
  files and directories created during use of Kolibri/Endless Key are
  owned by the correct user and group

Similarly we can assume that all preinstalled files are writable by
their owner, and that directories are executable as well as readable.

It is not necessary to mark files as executable: they are not executable
files, they are data. And doing so causes issues with live-booted
systems without persistant storage, where /var is an overlayfs with
upperdir and workdir stored on a tmpfs: to add the writable bit, the
files must be copied up to the writable directory. This quickly
fills the tmpfs, which can only occupy 50% of physical RAM; and the
system fails to boot.

Remove the Z line. Files on existing systems will keep the executable
bit – this is weird but harmless.

https://phabricator.endlessm.com/T35498

-----

You may ask yourself: why does overlayfs need to copy the file
contents to the upper directory just to change 3 bits in the
permissions?

From the overlayfs documentation
<https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html>:

> When a file in the lower filesystem is accessed in a way the requires
> write-access, such as opening for write access, changing some metadata
> etc., the file is first copied from the lower filesystem to the upper
> filesystem (copy_up).

There is a special mode that can be used to avoid this:

> When the “metacopy” feature is enabled, overlayfs will only copy up
> metadata (as opposed to whole file), when a metadata specific
> operation like chown/chmod is performed. Full file will be copied up
> later when file is opened for WRITE operation.

This feature can be enabled in 3 ways:

1. CONFIG_OVERLAY_FS_METACOPY can be set in the kernel configuration to
   enable this feature by default. We do not set this option in our
   kernel configuration.
2. The module parameter metacopy=on can be provided at module load time.
   We do not set this option at module load time.
3. The overlayfs can be mounted with metacopy=on. We do not set this
   option at mount time.

So why is this option not enabled by default? It is a security risk in
the general case:

> Do not use metacopy=on with untrusted upper/lower directories.
> Otherwise it is possible that an attacker can create a handcrafted
> file with appropriate REDIRECT and METACOPY xattrs, and gain access to
> file on lower pointed by REDIRECT. This should not be possible on
> local system as setting “trusted.” xattrs will require CAP_SYS_ADMIN.
> But it should be possible for untrusted layers like from a pen drive.

In our case the upper & lower directories are probably “trusted enough”
in the live-media case, because there are much easier ways to do
privilege escalation if you have access to the live media than tinkering
with the overlayfs.

This may be worth exploring in future but in this case we can just avoid
copying up gigabytes of data to set an unnecessary executable bit or
three.

### CODE REVIEW

**Comment by wjt** [comment]
(I tested `metacopy=on` locally and it had no effect: changing the mode bits on a file caused it to be copied up anyway.)

**Review by dbnicholson — COMMENTED** [review]
I think you're right. The lesser alternative is to leave the `Z` line there and stub out the mode with `-` so it just changes ownership. There's the possibility that someone runs kolibri as root (using the various management tools, for instance) and breaks normal Flatpak usage. However, I think that's going to be rare. A good fix there would be to check ownership on the Kolibri data directory and error if it doesn't match the caller's UID. That's out of scope, though.

**Comment by wjt** [comment]
@dbnicholson are you happy to go with this? Or would you like me to switch to the more conservative alternative that doesn't chmod?

**Comment by dbnicholson** [comment]
> @dbnicholson are you happy to go with this? Or would you like me to switch to the more conservative alternative that doesn't chmod?

Yes, but @dylanmccall noted that the [some share directories need to be world readable](https://phabricator.endlessm.com/T35498#997168), so I think you'd need to add:

```
d      @KOLIBRI_DATA_DIR@/content/xdg/share  0755  @KOLIBRI_USER@  @KOLIBRI_USER@  -    -
```

or something like that. It's possible that's not needed since the data directory is already world readable, but I think it's a good idea since we don't really know how that directory will be created on its own.

**Comment by wjt** [comment]
> > @dbnicholson are you happy to go with this? Or would you like me to switch to the more conservative alternative that doesn't chmod?
> 
> Yes, but @dylanmccall noted that the [some share directories need to be world readable](https://phabricator.endlessm.com/T35498#997168), so I think you'd need to add:
> 
> ```
> d      @KOLIBRI_DATA_DIR@/content/xdg/share  0755  @KOLIBRI_USER@  @KOLIBRI_USER@  -    -
> ```
> 
> or something like that. It's possible that's not needed since the data directory is already world readable, but I think it's a good idea since we don't really know how that directory will be created on its own.

In this PR I have not changed the permissions that tmpfiles will set on `/var/lib/kolibri` or `/var/lib/kolibri/data` – those are still 0755. While I think we should do that, it's separate to the issue I'm trying to fix here, of ISOs not booting.

We already rely on Kolibri setting appropriate permissions on `/var/lib/kolibri/data/content/xdg/share/applications` because, on images that did not come preinstalled with Kolibri content, tmpfiles will only create directories up to `/var/lib/kolibri/data` anyway.

I have tested as follows:

- Deleted `/var/lib/kolibri` in its entirety
- Applied the one-line change in this PR to `/etc/tmpfiles.d/eos-kolibri.conf`, masking the installed version
- Reboot
- Observe that `/var/lib/kolibri` and `/var/lib/kolibri/data` have been created, `kolibri:kolibri` and mode `0755`.
- Launched Kolibri. Installed an item of content.

```
drwxr-xr-x  6 kolibri kolibri    4096 Jul 11 15:54 /var/lib/kolibri/
drwxr-xr-x  6 kolibri kolibri    4096 Jul 11 15:56 /var/lib/kolibri/data
drwxr-xr-x  4 kolibri kolibri    4096 Jul 11 15:56 /var/lib/kolibri/data/content
drwxr-xr-x  3 kolibri kolibri    4096 Jul 11 15:56 /var/lib/kolibri/data/content/xdg
drwxr-xr-x  5 kolibri kolibri    4096 Jul 11 15:56 /var/lib/kolibri/data/content/xdg/share
drwxr-xr-x  2 kolibri kolibri    4096 Jul 11 15:56 /var/lib/kolibri/data/content/xdg/share/applications
-rw-r--r--  1 kolibri kolibri     483 Jul 11 15:56 /var/lib/kolibri/data/content/xdg/share/applications/org.learningequality.Kolibri.channel_bbb4ea407a3c450cb18cbaa76f2d75cd.desktop
```

The desktop launcher is shown in my session.

**Comment by dbnicholson** [comment]
> drwxr-xr-x  2 kolibri kolibri    4096 Jul 11 15:56 /var/lib/kolibri/data/content/xdg/share/applications

I suppose we're already relying on the fact that the service isn't running with a restrictive `umask` already since it would would be creating restricted files below world readable directories. I wonder why we even need `/var/lib/kolibri/data` then. `/var/lib/kolibri` is definitely needed since you need to be privileged to create it with `kolibri:kolibri` ownership, but once that's in place presumably the service can DTRT.

Whatever, not worth spending any more time on this for now.

**Review by dbnicholson — APPROVED** [review]

**Pull request merged**
